### ISSUE TITLE
How to setup in local environment?

### ISSUE THREAD

**Issue by NiroulaSantosh** [preet-adhikari/pl-match-data-api#8]
I am unable to run this project in  local machine. How to setup my local environment to run this project.  I'am interested in consuming those api mentioned. Please also provide link if this project is host in server.

**Comment by preet-adhikari** [comment]
Will update the docs promptly.

**Comment by preet-adhikari** [comment]
@NiroulaSantosh , I have updated the code and readme. You should now be able to run it on your local machine.
